### ISSUE TITLE
Possible to listen for Isotope filtering and sorting?

### ISSUE THREAD

**Issue by monster** [ressio/lazy-load-xt#11]
First off, really nice work on this. Definitely a big improvement on regular lazy-load. 

I'm curious if it's possible to have lazy-load-xt listen for when Isotope's filtering or sorting is fired? I have a grid of articles that have images within (using lazy-load-xt) and everything works totally fine except when you filter to something that's not initially within the viewport. It will only load the image when you scroll. 

```
$.extend($.lazyLoadXT, {
  edgeY:  200,
  srcAttr: 'data-src',
  blankImage: '/assets/img/loader-4x5.gif'
});

var $container = $('#archive');
// init
$container.isotope({
  // options
  itemSelector: '.issue-card',
  layoutMode: 'fitRows',
  getSortData: {
    name: '.name'
  }
});

// layout Isotope again after all images have loaded
$container.imagesLoaded( function() {
  $container.isotope('layout');
});

// filter items on button click
$('#filters').on( 'click', 'li', function() {
  var filterValue = $(this).attr('data-filter');
  $container.isotope({ filter: filterValue });
});

// sort items on button click
$('#sorts').on( 'click', 'li', function() {
  var sortByValue = $(this).attr('data-sort-by');
  $container.isotope({ sortBy: sortByValue });
});

// change is-checked class on buttons
$('.button-group').each( function( i, buttonGroup ) {
  var $buttonGroup = $( buttonGroup );
  $buttonGroup.on( 'click', 'li', function() {
    $buttonGroup.find('.is-checked').removeClass('is-checked');
    $( this ).addClass('is-checked');
  });
});
```

**Comment by Isodie** [comment]
I am trying to Implementing LazyLoad Xt on Masonry.js using code by @dryabov but it not helping.
<code> <script>
    // update event before window load/document ready
    $.lazyLoadXT.updateEvent += ' layoutComplete';


    // window load or document ready > see isotope docs
    $(window).load(function() { 

        var $container = $('.isotope').imagesLoaded(function(){
            $container.isotope({
                itemSelector: '.item',
                layoutMode: 'masonry'
            });

            // lazy update here             
            $container.isotope('on', 'layoutComplete', function() {
                $(window).trigger('layoutComplete');
            });

        });

        // filter stuff here... > see isotope docs

    });
</code><addr>

**Comment by o-l-e** [comment]
@Isodie try this:
http://jsfiddle.net/cd5L2056/13/

**Comment by Isodie** [comment]
@o-l-e 
Thanks for replying
Sorry I forgot to mention that I am also using Imageloaded and my item container width is in percentage.
If I keep its height and width constant its work.

**Comment by stedmanrh** [comment]
@o-l-e your fiddle is only loading the images because of the 'scroll' event (default behavior).
