### ISSUE TITLE
lazyloadxt with bootstrap carousel

### ISSUE THREAD

**Issue by richardguancn** [ressio/lazy-load-xt#67]
When I use lazyloadxt in my bootstrap carousel page,
It couldn't load the image when carousel auto slide.

Then, I use:
$(window).lazyLoadXT({ updateEvent: 'load orientationchange resize scroll touchmove focus slid.bs.carousel' });
also not work.

Must modify the jquery.lazyloadxt.min.js:
change this line:
updateEvent: "load orientationchange resize scroll touchmove focus"
to:
updateEvent: "load orientationchange resize scroll touchmove focus slid.bs.carousel"

then It is work when carousel auto slide.

**Comment by dryabov** [comment]
You use improper way to initialize LazyLoadXT. Instead, use

    $.lazyLoadXT.updateEvent += ' slid.bs.carousel';

**Comment by hassanamirkhan** [comment]
Now you can use this:
https://github.com/ressio/lazy-load-xt#bootstrap-and-jquerymobile
to handle it.
